workflow:
  rules:
    - if: $CI_MERGE_REQUEST_IID
    - if: $CI_COMMIT_TAG
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
    - if: $CI_PIPELINE_SOURCE == "web"

stages:
  - 00-configure-solution
  - 01-configured-test-solution
  - 02-revert-solution
  - 03-reverted-test-solution

default:
  image: "pingdevops.com/ci-utils/docker-builds-runner:edb6f37cedb342138aca215a69474e679b55390d5150ce8400eac264f2a864ae"
  services:
    - name: "docker:18.09-dind"
  tags:
    - k8s

variables:
  DOCKER_HOST: "tcp://localhost:2375"
  DOCKER_API_VERSION: "1.39"
  KUBERNETES_CPU_REQUEST: "1250m"
  KUBERNETES_CPU_LIMIT: "2000m"
  KUBERNETES_MEMORY_REQUEST: "2555Mi"
  KUBERNETES_MEMORY_LIMIT: "2555Mi"
  KUBERNETES_POLL_TIMEOUT: 600

configure-solution:
    stage: 00-configure-solution
    script:
      - "./.gitlab-ci/00-configure-solution.sh"

configured-test-solution:
    stage: 01-configured-test-solution
    script:
      - "./.gitlab-ci/01-configured-test-solution.sh"

revert-solution:
  stage: 02-revert-solution
  when: always
  script:
    - "./.gitlab-ci/02-revert-solution.sh"

reverted-test-solution:
  stage: 03-reverted-test-solution
  script:
    - "./gitlab-ci/03-reverted-test-solution.sh"
