- name: Solutions Pipeline Create Environment
  hosts: localhost
  connection: local
  gather_facts: false

  tasks:
  #destroy the CIAM Environment
  - name: CIAM Environment Deletion
    uri:
      url: '{{ API_LOCATION }}/environments/{{ CIAM_ENV_ID }}'
      method: DELETE
      headers:
        Authorization: "Bearer {{ PIPELINE_APP_ACCESS_TOKEN }}"
      body: ''
      status_code: 204
    register: ciam_env_del
    retries: 2

  #destroy the WF Environment
  - name: WF Environment Deletion
    uri:
      url: '{{ API_LOCATION }}/environments/{{ WF_ENV_ID }}'
      method: DELETE
      headers:
        Authorization: "Bearer {{ PIPELINE_APP_ACCESS_TOKEN }}"
      body: ''
      status_code: 204
    register: wf_env_del
    retries: 2