
- name: WF Get API Token
  uri:
    url: '{{AUTH_SERVER_BASE_URL}}/{{ ADMIN_ENV_ID }}/as/token'
    method: POST
    url_username: "{{ ADMIN_CLIENT_ID }}"
    url_password: "{{ ADMIN_CLIENT_SECRET }}"
    force_basic_auth: True
    body:
      "grant_type=client_credentials"
    headers:
      Content-Type: 'application/x-www-form-urlencoded'
    status_code: 200
  register: token_get
  retries: 2

- name: WF Set API Token
  set_fact:
    PIPELINE_APP_ACCESS_TOKEN: "{{ token_get.json.access_token }}"

- name: WF Get Env Info
  uri:
    url: '{{ API_LOCATION }}/environments/{{ ADMIN_ENV_ID }}'
    method: GET
    headers:
      Authorization: "Bearer {{ PIPELINE_APP_ACCESS_TOKEN }}"
    status_code: 200
  register: env_info
  retries: 2

- name: WF Get Environment Information
  set_fact: 
    org_id: "{{ env_info.json.organization.id }}"

- name: WF Get License Info
  uri:
    url: '{{ API_LOCATION }}/organizations/{{ org_id }}/licenses'
    method: GET
    headers:
      Authorization: 'Bearer {{ PIPELINE_APP_ACCESS_TOKEN }}'
    status_code: 200
  register: lic_info
  retries: 2  

- name: WF Get License Information
  set_fact:
    license_type: "{{ lic_info.json._embedded.licenses |
                  selectattr('name', 'match', 'INTERNAL') |
                  map(attribute='id') |
                  list | first }}"

- name: WF Random Env Info Set
  set_fact:
    timestamp: "{{ lookup('pipe', 'date +%s') }}"

- name: WF Set ENV Name
  set_fact:
    env_name: "Workforce_PIPELINE_{{ timestamp }}"

- name: WF Create New PingID Deployment
  uri:
    url: '{{ API_LOCATION }}/organizations/{{ org_id }}/deployments'
    method: POST
    headers:
      content-type: application/json
      Authorization: 'Bearer {{ PIPELINE_APP_ACCESS_TOKEN }}'
    body: >
      {
        "deploymentType": "PING_ENTERPRISE",
        "productType": "PING_ID",
        "status": "UNINITIALIZED"
      }
    body_format: json
    status_code: 201
  register: deploy_add
  retries: 2

- name: WF Get DeploymentID
  set_fact:
    deploymentId: "{{ deploy_add.json.id }}"

- name: WF Create New Environment
  uri:
    url: '{{ API_LOCATION }}/bootstraps'
    method: POST
    headers:
      content-type: application/json
      Authorization: 'Bearer {{ PIPELINE_APP_ACCESS_TOKEN }}'
    body: >
      {
          "inputs":{
            "environment":{
                "id":"",
                "name":"{{ env_name }}",
                "region":"NA",
                "type":"SANDBOX",
                "license":{
                  "id":"{{ license_type }}",
                  "name":"INTERNAL",
                  "supportedRegions":[
                      "EU",
                      "NORTH_AMERICA",
                      "AP"
                  ],
                  "allowProduction":false
                },
                "changeNotificationMessages":[
                
                ],
                "errors":{
                  "name":""
                },
                "organization":{
                  "id":"{{ org_id }}"
                },
                "billOfMaterials":{
                  "products":[
                      {
                        "type":"PING_ONE_BASE"
                      },
                      {
                        "type":"PING_ID",
                        "description": "PingID",
                        "deployment": {
                          "id": "{{ deploymentId }}"
                        },
                        "console": {
                          "href": "https://ort-admin.pingone.com/web-portal/cas/config/pingid"
                        }
                      },
                      {
                        "type":"PING_ONE_RISK"
                      },
                      {
                        "type":"PING_FEDERATE"
                      }
                  ]
                },
                "description":"Pipeline for Workforce"
            }
          },
          "type":"SAMPLE_DATA_TWO_POPULATIONS"
      }
    body_format: json
    status_code: 201
  register: env_add
  retries: 2

- name: WF Get Environment IDs
  uri:
    url: '{{ API_LOCATION }}/environments'
    method: GET
    headers:
      Authorization: 'Bearer {{ PIPELINE_APP_ACCESS_TOKEN }}'
    status_code: 200
  register: env_list    
  retries: 2  

- name: WF Save Values From New Environment
  set_fact:
      WF_ENV_ID: "{{ env_list.json._embedded.environments | 
                    selectattr('name','match', env_name ) |
                    map(attribute='id') | list | first }}"

- name: WF Get API Client Token
  uri:
    url: '{{AUTH_SERVER_BASE_URL}}/as/token.oauth2'
    method: POST
    url_username: "{{ API_CLIENT_ID }}"
    url_password: "{{ API_CLIENT_SECRET }}"
    force_basic_auth: True
    body:
      "grant_type=client_credentials"
    headers:
      Content-Type: 'application/x-www-form-urlencoded'
    status_code: 200
  register: client_token_get
  retries: 2

- name: WF Set API Token
  set_fact:
    WORKER_APP_ACCESS_TOKEN: "{{ client_token_get.json.access_token }}"

- name: WF Write Token to File
  lineinfile:
    dest: "/builds/solutions/thunder/.gitlab-ci/gitlab_var.prop"
    create: yes
    line: '{{ item }}'
  with_items:
    - "WF_ENV_NAME={{ env_name }}"
    - "WF_ENV_ID={{ WF_ENV_ID }}"

- name: WF Check if WORKER_APP_ACCESS_TOKEN is Already Defined
  lineinfile:
    state: absent
    path: "/builds/solutions/thunder/.gitlab-ci/gitlab_var.prop"
    regexp: "^WORKER_APP_ACCESS_TOKEN="
  check_mode: true
  changed_when: false # This just makes things look prettier in the logs
  register: worker_check

- name: WF Define WORKER_APP_ACCESS_TOKEN if Undefined
  lineinfile:
    state: present
    path: "/builds/solutions/thunder/.gitlab-ci/gitlab_var.prop"
    line: WORKER_APP_ACCESS_TOKEN={{ WORKER_APP_ACCESS_TOKEN }}
  when: worker_check.found == 0

- name: WF Check if PIPELINE_APP_ACCESS_TOKEN is Already Defined
  lineinfile:
    state: absent
    path: "/builds/solutions/thunder/.gitlab-ci/gitlab_var.prop"
    regexp: "^PIPELINE_APP_ACCESS_TOKEN="
  check_mode: true
  changed_when: false # This just makes things look prettier in the logs
  register: worker_check

- name: WF Define PIPELINE_APP_ACCESS_TOKEN if Undefined
  lineinfile:
    state: present
    path: "/builds/solutions/thunder/.gitlab-ci/gitlab_var.prop"
    line: PIPELINE_APP_ACCESS_TOKEN={{ PIPELINE_APP_ACCESS_TOKEN }}
  when: worker_check.found == 0

- name: WF Define Cypress.json file
  lineinfile:
    dest: "/builds/solutions/thunder/.gitlab-ci/cypress/WF_cypress.json"
    create: yes
    line: '{{ item }}'
  with_items:
    - '{'
    - '  "projectId": "{{ CYPRESS_PROJECT_ID }}",'
    - '  "pageLoadTimeout": 90000,'
    - '  "defaultCommandTimeout": 30000,'
    - '  "chromeWebSecurity": false,'
    - '  "env": {'
    - '    "baseUrl": "https://console-staging.pingone.com/?env={{ ADMIN_ENV_ID }}",'    
    - '    "ENV_ID": "{{ CIAM_ENV_ID }}",'
    - '    "ENV_NM": "{{ env_name }}",'
    - '    "CONSOLE_USERNAME": "{{ CONSOLE_USERNAME }}",'
    - '    "CONSOLE_PASSWORD": "{{ CONSOLE_PASSWORD }}"'
    - '    }'
    - '}'  

- name: WF Wait for PingID Deployment to be DEPLOYED
  uri:
    url: '{{ API_LOCATION }}/organizations/{{ org_id }}/deployments/{{ deploymentId }}'
    method: GET
    headers:
      Authorization: 'Bearer {{ PIPELINE_APP_ACCESS_TOKEN }}'
    status_code: 200
  register: ping_id_status
  until: ping_id_status.json.status == "DEPLOYED"
  retries: 20
  delay: 15
