apiVersion: v1
kind: Pod
metadata:
  name: testing-pf-post-playbook
spec:
  restartPolicy: Never
  containers:
    - name: testing-solutions
      image: pdsolutions/ansible_beluga:0.4@sha256:4fb94914a3a1d6752f0ab04cf084a6f4173aa13fd29e85e9c7d7a9b4822ca386
      imagePullPolicy: IfNotPresent
      resources:
        requests:
          cpu: 10m
          memory: 500Mi
        limits:
          cpu: 4
          memory: 8Gi
      env:
        - name: ENVIRONMENT_METADATA_JSON
          value:
            '{
              "pingOneInformation": {
                "organizationId": "",
                "webhookBaseUrl": "",
                "environmentId": "",
                "deploymentIds":
              { "pingfederate": "" }
              ,
              "environmentType": "dev"
              }
            }'
        - name: CLIENT_ID
          value: ""
        - name: CLIENT_SECRET
          value: ""
        - name: TOKEN_ENDPOINT
          value: ""
        - name: PINGFEDERATE_ADMIN_SERVER
          value: ""
        - name: PF_USERNAME
          value: ""
        - name: PF_PASSWORD
          value: ""
        - name: PF_ADMIN_PORT
          value: ""