- name: Get Token
  uri:
    url: '{{TOKEN_ENDPOINT}}'
    method: POST
    url_username: "{{ CLIENT_ID }}"
    url_password: "{{ CLIENT_SECRET }}"
    force_basic_auth: True
    body:
      "grant_type=client_credentials"
    headers:
      Content-Type: 'application/x-www-form-urlencoded'
    status_code: 200
  register: client_token_get
  retries: 2

- name: Set API Token
  set_fact:
    WORKER_APP_ACCESS_TOKEN: "{{ client_token_get.json.access_token }}"

- name: CIAM Risk Policy Check
  uri:
    url: '{{ API_LOCATION }}/environments/{{ ENV_ID }}/riskPolicySets'
    method: GET
    headers:
      Authorization: 'Bearer {{ WORKER_APP_ACCESS_TOKEN }}'
    status_code: 200
  register: risk_policy_result
  retries: 2

- name: 'Check risk policy name and get the ID'
  set_fact:
    risk_id: "{{ risk_policy_result.json._embedded.riskPolicySets[0].id }}"
    risk_name: "{{ risk_policy_result.json._embedded.riskPolicySets[0].name }}"

- name: CIAM Risk Policy Set ID
  uri:
    url: '{{ API_LOCATION }}/environments/{{ ENV_ID }}/riskPolicySets/{{ risk_id }}'
    method: PUT
    headers:
      content-type: application/json
      Authorization: 'Bearer {{ WORKER_APP_ACCESS_TOKEN }}'
    body: >
      {
        "name" : "Default CIAM Risk Policy",
        "default" : true,
        "canUseIntelligenceDataConsent": true,
        "description" : "For Use with PingFederate",
        "defaultResult" : {
          "level" : "LOW",
          "type" : "VALUE"
        },
        "riskPolicies" : [ {
          "name" : "GEOVELOCITY_ANOMALY",
          "priority" : 1,
          "result" : {
            "level" : "HIGH",
            "type" : "VALUE"
          },
          "condition" : {
            "equals" : true,
            "value" : "${details.impossibleTravel}"
          }
        },
        {
        "name" : "MEDIUM_WEIGHTED_POLICY",
        "priority" : 2,
        "result" : {
            "level" : "MEDIUM",
            "type" : "VALUE"
        },
        "condition" : {
            "between" : {
              "minScore" : 40,
              "maxScore" : 70
            },
            "aggregatedWeights" : [ {
              "value" : "${details.aggregatedWeights.anonymousNetwork}",
              "weight" : 4
              }, {
              "value" : "${details.aggregatedWeights.geoVelocity}",
              "weight" : 2
              }, {
              "value" : "${details.aggregatedWeights.ipRisk}",
              "weight" : 5
              }, {
              "value" : "${details.aggregatedWeights.userRiskBehavior}",
              "weight" : 0
              } ]
            }
          },
          {
          "name" : "HIGH_WEIGHTED_POLICY",
          "priority" : 3,
          "result" : {
            "level" : "HIGH",
            "type" : "VALUE"
          },
          "condition" : {
            "between" : {
              "minScore" : 70,
              "maxScore" : 100
            },
            "aggregatedWeights" : [ {
              "value" : "${details.aggregatedWeights.anonymousNetwork}",
              "weight" : 4
              }, {
              "value" : "${details.aggregatedWeights.geoVelocity}",
              "weight" : 2
              }, {
              "value" : "${details.aggregatedWeights.ipRisk}",
              "weight" : 5
              }, {
              "value" : "${details.aggregatedWeights.userRiskBehavior}",
              "weight" : 0
              } ]
            }
          } ]
        }
    body_format: json
    status_code: 200
  retries: 2
  when: 'risk_name != "Default CIAM Risk Policy"'