- name: CIAM User Modification Get Environment Information
  uri:
    url: '{{ API_LOCATION }}/environments/{{ ENV_ID }}'
    method: GET
    headers:
      Authorization: 'Bearer {{ WORKER_APP_ACCESS_TOKEN }}'
    status_code: 200
  register: env_info
  retries: 2

- name: CIAM User Modification Get the ORG ID and API endpoint
  set_fact: 
    orgID: "{{ env_info.json.organization.id }}"
    org_API: "{{ env_info.json._links.organization.href }}"                         

- name: CIAM User Modification ORG Environment query
  uri:
    url: '{{ org_API }}/environments'
    method: GET
    headers:
      Authorization: 'Bearer {{ WORKER_APP_ACCESS_TOKEN }}'
    status_code: 200
  retries: 2
  register: org_info   
  
- name: CIAM User Modification Get Admin Environment ID
  set_fact:
    adminENV: "{{ org_info.json._embedded.environments |
              selectattr('name', 'match', 'Administrators') |
              map(attribute='id') |
              list |
              first }}"  

- name: CIAM User Modification Get Users
  uri:
    url: '{{ API_LOCATION }}/environments/{{ adminENV }}/users'
    method: GET
    headers:
      Authorization: 'Bearer {{ WORKER_APP_ACCESS_TOKEN }}'
    status_code: 200
  retries: 2  
  register: admin_user_info

- name: CIAM User Modification Get User Data
  set_fact:
      admin_first: "{{ admin_user_info.json._embedded.users[0].name.given }}"
      admin_last: "{{ admin_user_info.json._embedded.users[0].name.family }}_Demo"
      admin_username: "{{ admin_user_info.json._embedded.users[0].username }}"
      admin_email: "{{ admin_user_info.json._embedded.users[0].email }}"

- name: CIAM User Modification Check Population in New Environment
  uri:
    url: '{{ API_LOCATION }}/environments/{{ ENV_ID }}/populations'
    method: GET
    headers:
      Authorization: 'Bearer {{ WORKER_APP_ACCESS_TOKEN }}'
    status_code: 200
  retries: 2
  register: pop_info

- name: CIAM User Modification Get Population ID
  set_fact:
    popID: "{{ pop_info.json._embedded.populations[0].id }}"

- name: CIAM User Modification Check Users in New Environment
  uri:
    url: '{{ API_LOCATION }}/environments/{{ ENV_ID }}/users'
    method: GET
    headers:
      Authorization: 'Bearer {{ WORKER_APP_ACCESS_TOKEN }}'
    status_code: 200
  retries: 2
  register: user_list

- name: CIAM User Modification List Users in New Environment
  set_fact:
    list_users: "{{ user_list.json._embedded.users |
                map(attribute='username') |
                list }}"

- name: CIAM User Modification Create User
  uri:
    url: '{{ API_LOCATION }}/environments/{{ ENV_ID }}/users'
    method: POST
    headers:
      content-type: 'application/json'
      Authorization: 'Bearer {{ WORKER_APP_ACCESS_TOKEN }}'
    body: >
      {
        "email": "{{ admin_email }}",
        "name": {
          "given": "{{ admin_first }}",
          "family": "{{ admin_last }}"
        },
        "population": {
          "id": "{{popID}}"
        },
        "username": "{{ admin_username }}",
      }
    body_format: json
    status_code: 201
  when: 'admin_username not in list_users'